### ISSUE TITLE
Library asserts when I have too little number of entities

### ISSUE THREAD

**Issue by bjadamson** [SuperV1234/ecst#7]
It seems like if I have A entities spawned on my pc, and the number of cores I have on my pc is B,

then if A is < B, my program dies.

I have been working on integrating ecst into my project and found this out, so I don't have a super small reproducable test case. I did observe this behavior directly though.

This was with inner_parallelism() on/off.

This is the assert that is triggerring:
https://github.com/SuperV1234/ecst/blob/master/include/ecst/context/system/instance/instance_subtask.inl#L61

My guess is there's a logic error, when the number of available entities is < the number of available cores, this assert is erroneously triggered.

**Comment by vittorioromeo** [comment]
Good catch. I think I've fixed the problem and other issues in the latest commits. Can you confirm the problem is resolved? 

Important notes:
- You need to make sure that `A >= B` before using the `split_evenly_fn::v_cores()` strategy. This was unclear - I've added an assert in the implementation of `split_evenly_fn` in 37371af795f9738b8d0345206c65c06450f6c9dc.
  - That can be done by composing strategies. Example:
    
    ``` cpp
    // One subtask under 10000 elements, otherwise split evenly per core count.
    namespace ips = ecst::inner_parallelism::strategy;
    namespace ipc = ecst::inner_parallelism::composer;
    ipc::none_below_threshold::v(sz_v<10000>, 
       ips::split_evenly_fn::v_cores()       
    );
    ```
- Empty entity ranges are allowed since b0d77d0a40162654c2c750def8c3ffbb3b032acc.

**Comment by bjadamson** [comment]
Confirmed working, all-though I think this should be persisted into some sort of FAQ.

**Comment by vittorioromeo** [comment]
Can this issue be closed?
